name: ngrouter
description: >
  Router for AngularDart.
  It enables navigation from one view to the next as users perform tasks.
version: 4.0.0-dev.3
repository: https://github.com/angulardart-community/angular

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  ngdart: ^8.0.0-dev.4

dev_dependencies:
  async: ^2.11.0
  build_runner: ^2.4.6
  build_test: ^2.2.1
  build_web_compilers: ^4.0.4
  lints: ^2.1.0
  mockito: ^5.4.3
  ngtest: ^5.0.0-dev.3
  test: ">=1.24.0 <1.25.0"
