name: ngrouter
repository: https://github.com/angulardart-community/angular
description: Router for AngularDart.
version: 3.2.0

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  ngdart: ^8.0.0
  collection: ^1.15.0
  js: ^0.6.3
  meta: ^1.3.0

dev_dependencies:
  async: ^2.5.0
  ngast: ^2.2.0
  ngcompiler: ^2.2.0
  ngtest: ^4.1.0
  build_runner: ^2.0.0
  build_test: ^2.0.0
  build_web_compilers: ^3.0.0
  mockito: ^5.0.0
  pedantic: ^1.10.0
  test: ^1.16.0

# added for local builds
dependency_overrides:
  ngdart:
    path: ../ngdart
  ngcompiler:
    path: ../ngcompiler
  ngtest:
    path: ../ngtest
  ngast:
    path: ../ngast
