name: ngast
description: Parser and utilities for AngularDart templates
version: 3.0.0-dev.1
repository: https://github.com/angulardart-community/angular

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  charcode: ^1.3.1
  collection: ^1.18.0
  meta: ^1.11.0
  source_span: ^1.10.0
  string_scanner: ^1.2.0

dev_dependencies:
  lints: ^2.1.0
  path: ^1.8.3
  test: ">=1.24.0 <1.25.0"
