name: ngcompiler
description: >
  The AngularDart compiler.
  It compiles your component files written in Dart into templates so that you
  don't have to worry about all the complicated hassle.
version: 3.0.0-dev.3
repository: https://github.com/angulardart-community/angular

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  analyzer: ^6.0.0
  args: ^2.4.2
  build: ^2.4.1
  code_builder: ^4.7.0
  collection: ^1.18.0
  csslib: ^1.0.0
  dart_style: ^2.3.2
  logging: ^1.2.0
  meta: ^1.11.0
  ngast: ^3.0.0-dev.2
  ngdart: ^8.0.0-dev.4
  path: ^1.8.3
  source_gen: ^1.4.0
  source_span: ^1.10.0

dev_dependencies:
  build_test: ^2.2.1
  lints: ^2.1.0
  package_config: ^2.1.0
  test: ">=1.24.0 <1.25.0"
