name: ngforms
repository: https://github.com/angulardart-community/angular
description: Forms framework for AngularDart.
version: 4.1.0

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  ngdart: ^8.0.0
  meta: ^1.3.0

dev_dependencies:
  ngcompiler: '>=2.2.0 <3.0.0'
  ngast: ^2.2.0
  ngtest: ^4.1.0
  build_runner: ^2.0.0
  build_test: ^2.0.0
  build_web_compilers: ^3.0.0
  mockito: ^5.0.0
  pedantic: ^1.10.0
  test: ^1.16.0

# added for local builds
dependency_overrides:
  ngdart:
    path: ../ngdart
  ngtest:
    path: ../ngtest
  ngcompiler:
    path: ../ngcompiler
  ngast:
    path: ../ngast
