name: ngtest
description: >
  Testing runner and library for AngularDart.
  This package is necessary to write component tests for AngularDart components.
version: 5.0.0-dev.2
repository: https://github.com/angulardart-community/angular

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  meta: ^1.11.0
  ngdart: ^8.0.0-dev.3

dev_dependencies:
  build_runner: ^2.4.6
  build_test: ^2.2.1
  build_web_compilers: ^4.0.4
  lints: ^2.1.0
  test: ^1.24.4
